[package]
name = "rust-yap"
version = "0.1.0"
authors = ["Maciej Dziardziel <fiedzia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.9.0"
indexmap = "1.5.1"
derivative = "2.1.1"
